// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfprwecostlvlvhuavgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmcHJ3ZWNvc3Rsdmx2aHVhdmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzk1MTEsImV4cCI6MjA1ODgxNTUxMX0.HqPQvDZeWsf60WyiXFSUVc5fOj51T7tEHVqlYdWYiec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);